### ISSUE TITLE
v1.8 shortlist

### ISSUE THREAD

**Issue by smithdc1** [django-crispy-forms/django-crispy-forms#906]
Hi @carltongibson ,

I thought I'd put together a shortlist for the 1.8 release. I think there are a few 'easy' issues that could be closed. 

- [x] Review #899 fixes #798 
- [x] Re-work #868 to extract fix for #861 
- [x] Review #881 fixes #859 
- [x] Investigate #793 as we have looked at this code recently, #794 also did some work. 
- [x] #904 would be nice, but only if @Gilbishkosma has time. 

The other thing I was going to put on the list was about reviewing / updating the docs. I notice that RTD doesn't seem that up to date so I may be looking in the wrong place? 

Therefore key changes in 1.8 are:

1. Django 3.0 compatibility
2. Various improvements to BS4. (Incl. File field, error labels and xl size)

Hope this is helpful!? Anything else you think is missing?

**Comment by Gilbishkosma** [comment]
@smithdc1  sure , i will see the #904

**Comment by carltongibson** [comment]
Hey @smithdc1. I ticked off a couple. I will look at Django 3.0 compat (I think we're there already really…). Then we're not far off. Thanks for your input!

**Comment by smithdc1** [comment]
Thanks Carlon.

I've had a look at the second item on the list. Having tried to reproduce the issue it looks like it's already been fixed, I've therefore closed the issue and the related PR (hope this is ok!). There is still something in the way `label=false` renders for booleans but I don't there is a use case for boolean without a label and I've not come across an issue raised for this. 

Another step closer 😃

**Comment by myartsev** [comment]
Hi! Any idea for the timing of the 1.8 release? It's been ~1.5 years since the last one and there are a few fixes that'd be nice to have as an official release 🚀

**Comment by smithdc1** [comment]
Hi @myartsev, we are close. I closed off the 4th item on the list over the weekend so just one task remaining (which _I think_ is a nice to have)
@carltongibson is there anything else we need to do (or that I can help with?) before the next release?
